// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqY8fjne42pstwPvJd1mpYuND0QgVKlG4',
    appId: '1:111382315348:android:519044f5a87262735508c1',
    messagingSenderId: '111382315348',
    projectId: 'babaal-patro',
    storageBucket: 'babaal-patro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRwwNlnGOkTEzBh-lrFyV_M39wy9Tnu-I',
    appId: '1:111382315348:ios:0991801a2a4330d15508c1',
    messagingSenderId: '111382315348',
    projectId: 'babaal-patro',
    storageBucket: 'babaal-patro.firebasestorage.app',
    iosClientId: '111382315348-dokhkffrh89srge7sq7ajobpkclild2s.apps.googleusercontent.com',
    iosBundleId: 'com.babaal.patro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qp9ghjmiosfNkqAKuiQ1rxCQI4RZ4fk',
    appId: '1:111382315348:web:a233a5f7f59be6c75508c1',
    messagingSenderId: '111382315348',
    projectId: 'babaal-patro',
    authDomain: 'babaal-patro.firebaseapp.com',
    storageBucket: 'babaal-patro.firebasestorage.app',
    measurementId: 'G-SDWYER0V2N',
  );

}